version: '2'
services:
  ecomercetest-app:
    image: ecomercetest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://ecomercetest-mysql:3306/ecomercetest?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://ecomercetest-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://ecomercetest-elasticsearch:9200
    ports:
      - 8080:8080
  ecomercetest-mysql:
    extends:
      file: mysql.yml
      service: ecomercetest-mysql
  ecomercetest-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: ecomercetest-elasticsearch
